---
- name: Update Apt cache
  apt:
    update_cache: yes
    cache_valid_time: "86400"  # One day
  register: _update_apt_cache
  until: _update_apt_cache is success
  retries: 3
  delay: 2

- name: Ensure unzip exists
  apt:
    name: unzip
    state: present

- import_tasks: packer.yml
- import_tasks: terraform.yml
- import_tasks: vault.yml
