---
- name: Converge
  hosts: all
  vars:
    install_packer: yes
    install_terraform: yes
    install_vault: yes
  tasks:
    - name: Include role
      include_role:
        name: vladgh.hashicorp
